image: k33g/capsule:0.0.1

tasks:
  - name: initialize
    before: |
      echo "💊 Installing capsule..."
      wget https://github.com/bots-garden/capsule/releases/download/0.0.6/capsule-0.0.6-linux-amd64.tar.gz
      sudo tar -zxf capsule-0.0.6-linux-amd64.tar.gz --directory /usr/local/bin
      rm capsule-0.0.6-linux-amd64.tar.gz
    init: |
      echo "🚀 Get Golang hostfunctions package..."
      cd 01-cli-say-hello
      go get github.com/bots-garden/capsule/capsulemodule/hostfunctions
      cd ..
      clear

ports:
  - port: 8090-21300
    onOpen: ignore
  - port: 8080
    visibility: public
  - port: 3000
    visibility: public
  - port: 5000
    visibility: public
  - port: 7070
    visibility: public
  - port: 8091
    visibility: public
  - port: 4369
    onOpen: ignore


vscode:
  extensions:
    - golang.go
    - pkief.material-icon-theme
    - aaron-bond.better-comments
